version: '3.4'
services:
  lighthouse:
    image: petabridge/lighthouse:v0.9.2
    ports:
      # Port 9110 is exposed so as to allow the Petrabridge.cmd client (https://cmd.petabridge.com/)
      # to connect to it. The lighthouse includes the Petabridge cluster extension allowing one to
      # easily view connected nodes
      - '9110:9110'
      # Port 4053 is used by lighthouse for inter-actor communication
      - '4053:4053'
    environment:
      ACTORSYSTEM: "playground"
      # The cluster IP (bit of a misnomer, here it's the hostname) is derived from the service name (lighthouse)
      CLUSTER_IP: lighthouse
      CLUSTER_PORT: 4053
      CLUSTER_SEEDS: "akka.tcp://playground@lighthouse:4053"
  playground.web:
    # Injected by visual studio, which messes with the image
    image: ${DOCKER_REGISTRY-}playgroundweb
    build:
      context: .
      dockerfile: src/Playground.Web/Dockerfile
      target: runner
    ports:
      # Api port
      - "5050:5050"
      # Port used for inter-actor communication. Possibly should standardise on a particular port 
      - '4054:4053'
      # Map port 9110 to 9111. Port 9111 is used to connect to Petabridge.cmd for this node
      - '9111:9110'
    depends_on:
      - playground.worker.1
      - playground.worker.2
      - lighthouse
    environment:
      ASPNETCORE_ENVIRONMENT: local    
  playground.worker.1:
    # Injected by visual studio, which messes with the image
    image: ${DOCKER_REGISTRY-}playgroundworker
    build:
      context: .
      dockerfile: src/Playground.Worker/Dockerfile
      target: runner
    ports:      
      # Port used for inter-actor communication. Possibly should standardise on a particular port 
      - '4055:4053'
      # Map port 9110 to 9112. Port 9112 is used to connect to Petabridge.cmd for this node
      - '9112:9110'
    depends_on:      
      - lighthouse
    environment:
      ASPNETCORE_ENVIRONMENT: local
      CLUSTER_IP: playground.worker.1
      CLUSTER_PORT: 4055
  playground.worker.2:
    # Injected by visual studio, which messes with the image
    image: ${DOCKER_REGISTRY-}playgroundworker
    build:
      context: .
      dockerfile: src/Playground.Worker/Dockerfile
      target: runner
    ports:
      # Port used for inter-actor communication. Possibly should standardise on a particular port 
      - '4056:4053'
      # Map port 9110 to 9112. Port 9112 is used to connect to Petabridge.cmd for this node
      - '9113:9110'
    depends_on:
      - lighthouse
    environment:
      ASPNETCORE_ENVIRONMENT: local
      CLUSTER_IP: playground.worker.2
      CLUSTER_PORT: 4056
